apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ntir
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fggo-tenant/rhtap-demo-app/hacbs-test-project-ntir@sha256:1081be1297884420c9003bb0a44a4cc39f34542631be55d53665ff2e5024088d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
